export const CUSTOMER_API_BASE = '/api/customer';
export const CUSTOMER_MANY_URL = CUSTOMER_API_BASE;
export const CUSTOMER_GET_URL = CUSTOMER_API_BASE;
export const CUSTOMER_CREATE_URL = CUSTOMER_API_BASE;
export const CUSTOMER_UPDATE_URL = CUSTOMER_API_BASE;
export const CUSTOMER_DELETE_URL = CUSTOMER_API_BASE;